-- MySQL Script generated by MySQL Workbench
-- Wed Feb 18 15:10:18 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema columnav_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema columnav_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `columnav_db` DEFAULT CHARACTER SET utf8mb3 ;
USE `columnav_db` ;

-- -----------------------------------------------------
-- Table `columnav_db`.`rooms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `columnav_db`.`rooms` (
  `room_id` INT NOT NULL AUTO_INCREMENT,
  `room_name` VARCHAR(150) NOT NULL,
  `room_description` TINYTEXT NULL DEFAULT NULL,
  `floor_number` INT NOT NULL,
  `is_active` TINYINT(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`room_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 110
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `columnav_db`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `columnav_db`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(100) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `role` VARCHAR(45) NULL DEFAULT 'admin',
  `is_active` TINYINT(1) NULL DEFAULT '1',
  `updated_at` DATETIME NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
